feat(post-merge): conditionally run build script based on dev server lock file presence

diff --git a/.husky/post-merge b/.husky/post-merge
--- a/.husky/post-merge
+++ b/.husky/post-merge
@@ -89,14 +89,18 @@ fi
 node --no-warnings=ExperimentalWarning --loader ts-node/esm "$CWD/src/dev/git-history.builder.ts"
 
 # Run yarn
+ViteLockFile="$CWD/tmp/locks/.dev-server-lock"
 if command -v yarn >/dev/null 2>&1; then
   touch "$CWD/yarn.lock"  # Create an empty yarn.lock if it doesn't exist
   yarn install || {
     echo "Yarn install failed."
   }
-  node "$CWD/bin/build-project.mjs" || {
-    echo "Build project failed."
-  }
+  # Run the build script when the lock file is not present
+  if [ ! -f "$ViteLockFile" ]; then
+    node "$CWD/bin/build-project.mjs" || {
+      echo "Build project failed."
+    }
+  fi
 else
   echo "Error: Yarn is not installed. Skipping yarn operations."
 fi
