fix(husky): husky script deprecated

diff --git a/.husky/post-commit b/.husky/post-commit
--- a/.husky/post-commit
+++ b/.husky/post-commit
@@ -4,21 +4,8 @@
 SCRIPT_DIR=$(dirname "$(realpath "$0")")
 PROJECT_DIR=$(dirname "$SCRIPT_DIR")
 
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+command -v git-lfs >/dev/null 2>&1 || {
+  echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"
+  exit 2
+}
 git lfs post-commit "$@"
-
-# Path to the Husky script
-HUSKY_SH="$(dirname "$0")/_/husky.sh"
-
-# Check if the Husky script exists
-if [ -f "$HUSKY_SH" ]; then
-  # Source the Husky script to run Husky hooks
-  . "$HUSKY_SH"
-else
-  echo "Husky script not found: $HUSKY_SH"
-  exit 1
-fi
-
-
-
-
